### ISSUE TITLE
Any possibility for an iPhone version?

### ISSUE THREAD

**Issue by shiitake** [sparkfunX/Skimmer_Scanner#2]
Looks like this was written with Xamarin - which might make it a bit easier to include iPhone.

**Comment by NPoole** [comment]
I don't have access to a mac to provide the build environment/dependencies/etc for Xamarin.iOS but if you know someone who would like to take a crack at it, I'd be happy to pull it.

**Comment by samuelitor** [comment]
Just a heads up, but I was curious about this exact possibility and did some cursory research into whether or not it would be possible and unfortunately it doesn't look like it's possible to get an app into the app store doing this function.

HC-05 relies on classic bluetooth and neither CoreBluetooth nor External Accessories will provide APIs that you can use to a) connect and b) transmit data back and forth to the skimmers. 

See:
https://electronics.stackexchange.com/questions/253711/connecting-to-hc-05-from-ios-based-device/253712
and
https://stackoverflow.com/questions/18214023/how-to-use-bluetooth-classic-instead-of-le

If you wanted to go as far as to create an app not for distribution that can at lease detect the presence of pumps transmitting a HC-05 id, you can use this library which uses private APIs that are banned by apple:
https://github.com/michaeldorner/BeeTee

**Comment by stephenyeargin** [comment]
Getting it in the app store aside, having an open source version that can be side loaded through Xcode on to a device would be 👍. (Though I believe the build certificate expires after seven days, so it wouldn't be perfect.)

**Comment by trparky** [comment]
I have seen other Bluetooth scanners so I can't imagine why this one can't be done.

**Comment by deisterhold** [comment]
@trparky The other bluetooth scanning apps only see BLE devices and not Bluetooth 2.0 devices.
