### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by EarlyMon** [sparkfunX/Skimmer_Scanner#3]
Crashes during scanning and about. I'm rooted so gathering logs is easy - any in particular that I can help with?

**Comment by strasharo** [comment]
Same here, scanned once and it crashes on every launch now.

**Comment by NPoole** [comment]
I found the bug, it's a context passing error. An update has been pushed to the Play Store. I'm working on getting the new source up here but my Git permissions are mangled.

**Comment by wjcarpenter** [comment]
Thanks for the fast fix. The crash hit me, too. I confirm that the fix worked on my Nexu 5 (Android 6.0.1)

**Comment by EarlyMon** [comment]
Works for me, well done, many thanks!
