### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by Poussinou** [sparkfunX/Skimmer_Scanner#9]
Can you please tag your releases (see [here](https://help.github.com/articles/creating-releases/)), it would be helpful for the F-Droid release (Request For Packaging [here](https://gitlab.com/fdroid/rfp/issues/353)). You could also attach the binaries to your releases (see [here](https://blog.github.com/2013-07-02-release-your-software/)).

That's pretty easy and very helpful for those of us who aren't using Google services.

**Comment by NPoole** [comment]
So sorry for the delay in doing this. F-Droid inclusion has stalled on my end as I look for a more OSS-friendly build process than the Visual Studio solution that I'm currently using.

**Comment by NPoole** [comment]
See V_1.4.0 release [here](https://github.com/sparkfunX/Skimmer_Scanner/releases/tag/V_1.4.0)

**Comment by Poussinou** [comment]
No problem. Do not forget to tag new releases when they are published.

I don't know if F-Droid can handle C# applications, someone else will have a look at this, I'm not good enough...

#1
